# Reference: https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages

on:
  push:
    branches: [ main ]
    
jobs:
  deploy-ui-to-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0
        include-prerelease: true

    - name: Publish HomeBalls.App.UI
      run: dotnet publish .\src\HomeBalls.App.UI\CEo.Pokemon.HomeBalls.App.UI.csproj -c Release -o .\release --nologo

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .\release\wwwroot
